# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

-   repo: https://github.com/crate-ci/typos
    rev: v1.27.3
    hooks:
      - id: typos

-   repo: https://github.com/Takishima/cmake-pre-commit-hooks
    rev: v1.8.0
    hooks:
      - id: clang-format
        args: [-i]
      - id: clang-tidy
        args: [--checks=readability-magic-numbers,--warnings-as-errors=*]
#      - id: cppcheck
#        args: [--std=c++20,--enable=all]
